export const SHARED_TAXONOMIES = [
  {
    id: "source-types",
    label: "Source Types",
    type: "Taxonomy",
    status: "published",
    values: [
      "Animal",
      "Architecture",
      "Biological Process",
      "Book History",
      "Chemical Hazard",
      "Film",
      "Folklore",
      "Funerary Object",
      "Funerary Practice",
      "Historical Weapon",
      "Literature",
      "Material Culture",
      "Religious Tale",
      "Ritual",
      "Sacred Site",
    ],
  },
  {
    id: "horror-modes",
    label: "Horror Modes",
    type: "Taxonomy",
    status: "published",
    values: [
      "Body Horror",
      "Cosmic Horror",
      "Disease Horror",
      "Folk Horror",
      "Gothic",
      "Occult Horror",
      "Predatory Horror",
      "Psychological Horror",
      "Religious Horror",
      "Survival Horror",
      "War Horror",
    ],
  },
  {
    id: "content-statuses",
    label: "Content Statuses",
    type: "Taxonomy",
    status: "published",
    values: ["draft", "published", "archived"],
  },
];
